version: '3.1'

services:

  web:
    image: redmine
    restart: always
    ports:
      - 3000:3000
    volumes:
      - files:/usr/src/redmine/files
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD=redminepassword
      - REDMINE_SECRET_KEY_BASE=redminesecretkey
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=redmine
      - MYSQL_PASSWORD=redminepassword
      - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  files:
  mysql:
